# sync-rules.ps1 -- Synchronize Kuro Rules to all git repos
# Usage: .\sync-rules.ps1 [-Force] [-DryRun] [-Project <name>]
param(
    [switch]$Force,
    [switch]$DryRun,
    [string]$Project
)

$ErrorActionPreference = "Stop"
$RULES_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $RULES_DIR "KuroUtils.psm1") -Force

# Configuration
$RULE_FILES = @(
    "AGENTS.md",
    ".cursorrules",
    "copilot-instructions.md",
    ".windsurfrules",
    "AI_GUIDELINES.md"
)

# 1. GENERATE SMART REDIRECTOR (AGENTS.md) for deployment
$compiledPath = Join-Path $RULES_DIR "AGENTS_REDIRECTOR.tmp.md"
Write-KuroLog "Generating Smart Redirector with index..." -Color Cyan
try {
    $ruleFiles = Get-ChildItem (Join-Path $RULES_DIR "rules") -Filter "rule_*.md" | Sort-Object Name
    
    $index = "# AGENTS.md -- Kuro Rules Redirector`n"
    $index += "# DO NOT EDIT THIS FILE DIRECTLY. Master rules are in: ~/Documents/kuro-rules/rules/`n`n"
    $index += "You MUST read the rules relevant to your current task. Read R1 first.`n"
    $index += "To read a rule, use your 'view_file' tool on the corresponding file in the master folder.`n`n"
    $index += "## Rule Index`n"
    
    foreach ($rf in $ruleFiles) {
        $title = (Get-Content $rf.FullName -TotalCount 1).Trim('# ')
        $index += "- **$($rf.BaseName)**: $title`n"
    }
    
    [System.IO.File]::WriteAllText($compiledPath, $index, [System.Text.Encoding]::UTF8)
    Write-KuroLog "  OK: Smart Redirector generated with $($ruleFiles.Count) entries." -Color DarkGray
} catch {
    Write-KuroLog "  ERROR: Failed to generate index: $_" -Color Red
    exit 1
}

# 2. DISCOVER PROJECTS
$projects = Get-KuroProjects
if ($Project) {
    $projects = $projects | Where-Object { $_.Name -eq $Project }
    if (-not $projects) { Write-KuroLog "ERROR: '$Project' not found" -Color Red; exit 1 }
}

Write-KuroLog "Starting sync for $($projects.Count) projects..." -Color Gray
if ($DryRun) { Write-KuroLog "[DRY RUN ENABLED]" -Color Yellow }

$syncCount = 0
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$logEntries = @()

foreach ($proj in $projects) {
    $projSynced = @()
    foreach ($file in $RULE_FILES) {
        $src = Join-Path $RULES_DIR $file
        if ($file -eq "AGENTS.md") { $src = $compiledPath }
        
        $dst = Join-Path $proj.Path $file
        if ($file -eq "copilot-instructions.md") {
            $githubDir = Join-Path $proj.Path ".github"
            if (Test-Path $githubDir) { $dst = Join-Path $githubDir $file }
        }

        if (-not (Test-Path $src)) { continue }

        $needsSync = $false
        if (-not (Test-Path $dst)) { $needsSync = $true }
        elseif ($Force) { $needsSync = $true }
        else {
            $srcHash = (Get-FileHash $src -Algorithm MD5).Hash
            $dstHash = (Get-FileHash $dst -Algorithm MD5).Hash
            if ($srcHash -ne $dstHash) { $needsSync = $true }
        }

        if ($needsSync) {
            if (-not $DryRun) { Copy-Item $src $dst -Force }
            $projSynced += $file
            $syncCount++
        }
    }

    if ($projSynced.Count -gt 0) {
        Write-KuroLog "  SYNCED -> $($proj.Name) ($($projSynced -join ', '))" -Color Green
        $logEntries += "- $($proj.Name) : $($projSynced -join ', ')"
    }
}

# 3. UPDATE LOG
if (-not $DryRun -and $logEntries.Count -gt 0) {
    $logFile = Join-Path $RULES_DIR "SYNC_LOG.md"
    $logHeader = "## $timestamp`n"
    $logBody = ($logEntries -join "`n") + "`n`n"
    if (Test-Path $logFile) {
        $existing = Get-Content $logFile -Raw
        $newContent = "# Sync Log`n`n" + $logHeader + $logBody + ($existing -replace "^# Sync Log\s*\n*", "")
    } else { $newContent = "# Sync Log`n`n" + $logHeader + $logBody }
    [System.IO.File]::WriteAllText($logFile, $newContent, [System.Text.Encoding]::UTF8)
}

# Cleanup
if (Test-Path $compiledPath) { Remove-Item $compiledPath -Force }
Write-KuroLog "Done. Total syncs: $syncCount" -Color Cyan