# sync-rules.ps1 -- Synchronize Kuro Rules to all git repos
# Usage: .\sync-rules.ps1 [-Force] [-DryRun] [-Project <name>] [-SkipOwnershipCheck]
# Per R87: EXTERNAL repos receive ONLY AGENTS.md (the redirector), never the full rule files.
# Per R105: workspace/submodule/cross-repo projects are still synced individually.
param(
    [switch]$Force,
    [switch]$DryRun,
    [string]$Project,
    [switch]$SkipOwnershipCheck
)

$ErrorActionPreference = "Stop"
$RULES_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $RULES_DIR "KuroUtils.psm1") -Force

# Full rule file set (OWNED only)
$RULE_FILES_FULL = @(
    "AGENTS.md",
    ".cursorrules",
    "copilot-instructions.md",
    ".windsurfrules",
    "AI_GUIDELINES.md"
)

# Redirector only (OWNED + EXTERNAL)
$RULE_FILES_REDIRECTOR = @(
    "AGENTS.md"
)

# 1. GENERATE SMART REDIRECTOR (AGENTS.md) for deployment
$agentsPath = Join-Path $RULES_DIR "AGENTS.md"
Write-KuroLog "Generating Smart Redirector with index..." -Color Cyan
try {
    $ruleFiles = Get-ChildItem (Join-Path $RULES_DIR "rules") -Filter "rule_*.md" | Sort-Object Name

    $index = "# AGENTS.md -- Kuro Rules Redirector`n"
    $index += "# DO NOT EDIT THIS FILE DIRECTLY. Master rules are in: ~/Documents/kuro-rules/rules/`n`n"
    $index += "You MUST read the rules relevant to your current task. Read R1 first.`n"
    $index += "To read a rule, use your 'view_file' tool on the corresponding file in the master folder.`n`n"
    $index += "## Rule Index`n"

    foreach ($rf in $ruleFiles) {
        $title = (Get-Content $rf.FullName -TotalCount 1).Trim('# ')
        $index += "- **$($rf.BaseName)**: $title`n"
    }

    if ($DryRun) {
        # CI-verifiable : ne jamais ecrire en DryRun, signaler le drift (B2).
        $current = ""
        if (Test-Path $agentsPath) { $current = [System.IO.File]::ReadAllText($agentsPath) }
        if ($current -ne $index) {
            Write-KuroLog "  DRIFT: AGENTS.md index serait regenere ($($ruleFiles.Count) entrees)." -Color Yellow
        } else {
            Write-KuroLog "  OK: Smart Redirector a jour ($($ruleFiles.Count) entries)." -Color DarkGray
        }
    } else {
        [System.IO.File]::WriteAllText($agentsPath, $index, [System.Text.Encoding]::UTF8)
        Write-KuroLog "  OK: Smart Redirector generated with $($ruleFiles.Count) entries." -Color DarkGray
    }
} catch {
    Write-KuroLog "  ERROR: Failed to generate index: $_" -Color Red
    exit 1
}

# 2. DISCOVER PROJECTS
$projects = Get-KuroProjects
if ($Project) {
    $projects = $projects | Where-Object { $_.Name -eq $Project }
    if (-not $projects) { Write-KuroLog "ERROR: '$Project' not found" -Color Red; exit 1 }
}

Write-KuroLog "Starting sync for $($projects.Count) projects..." -Color Gray
if ($DryRun) { Write-KuroLog "[DRY RUN ENABLED]" -Color Yellow }

$syncCount = 0
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$logEntries = @()

foreach ($proj in $projects) {
    $projSynced = @()

    # R87: Pick the file set based on ownership
    $ownership = $proj.Ownership
    if ($SkipOwnershipCheck) {
        $ruleFilesForProj = $RULE_FILES_FULL
    } elseif ($ownership -eq "EXTERNAL") {
        $ruleFilesForProj = $RULE_FILES_REDIRECTOR
        Write-KuroLog "  EXTERNAL: $($proj.Name) -- AGENTS.md only (R87)" -Color DarkYellow
    } elseif ($ownership -eq "UNKNOWN") {
        $ruleFilesForProj = $RULE_FILES_REDIRECTOR
        Write-KuroLog "  UNKNOWN: $($proj.Name) -- AGENTS.md only (R87, no remote classification)" -Color DarkYellow
    } else {
        $ruleFilesForProj = $RULE_FILES_FULL
    }

    foreach ($file in $ruleFilesForProj) {
        $src = Join-Path $RULES_DIR $file

        $dst = Join-Path $proj.Path $file
        if ($file -eq "copilot-instructions.md") {
            $githubDir = Join-Path $proj.Path ".github"
            if (-not (Test-Path $githubDir)) { New-Item -ItemType Directory -Path $githubDir -Force | Out-Null }
            $dst = Join-Path $githubDir $file
        }

        if (-not (Test-Path $src)) { continue }

        $needsSync = $false
        if (-not (Test-Path $dst)) { $needsSync = $true }
        elseif ($Force) { $needsSync = $true }
        else {
            $srcHash = (Get-FileHash $src -Algorithm MD5).Hash
            $dstHash = (Get-FileHash $dst -Algorithm MD5).Hash
            if ($srcHash -ne $dstHash) { $needsSync = $true }
        }

        if ($needsSync) {
            if (-not $DryRun) { Copy-Item $src $dst -Force }
            $projSynced += $file
            $syncCount++
        }
    }

    # --- R112: standard tooling pre-commit (OWNED uniquement, C) ---
    # Source: templates/.pre-commit-config.yaml (générique). Ne jamais écraser
    # une config locale customisée sauf -Force. DryRun-aware pour CI.
    $isOwnedForTooling = $SkipOwnershipCheck -or ($ownership -eq "OWNED")
    if ($isOwnedForTooling) {
        $preSrc = Join-Path $RULES_DIR "templates\.pre-commit-config.yaml"
        $preDst = Join-Path $proj.Path ".pre-commit-config.yaml"
        if (Test-Path $preSrc) {
            $needPre = $false
            if (-not (Test-Path $preDst)) { $needPre = $true }
            elseif ($Force) { $needPre = $true }
            if ($needPre) {
                if (-not $DryRun) { Copy-Item $preSrc $preDst -Force }
                $projSynced += ".pre-commit-config.yaml (R112)"
                $syncCount++
            }
        }
    }

    # --- ALWAYS-ON: compliance workflow + manifest (enforcement CI, tous repos) ---
    # En DryRun: verifie le drift du workflow sans ecrire (CI-verifiable, B2).
    $wfSrc = Join-Path $RULES_DIR "templates\kuro-compliance.yml"
    $wfDst = Join-Path $proj.Path ".github\workflows\kuro-compliance.yml"
    $wfDrift = $false
    if (Test-Path $wfSrc) {
        if (-not (Test-Path $wfDst)) { $wfDrift = $true }
        else {
            $srcHash = (Get-FileHash $wfSrc -Algorithm MD5).Hash
            $dstHash = (Get-FileHash $wfDst -Algorithm MD5).Hash
            if ($srcHash -ne $dstHash) { $wfDrift = $true }
        }
    }
    if ($wfDrift) {
        $projSynced += ".github/workflows/kuro-compliance.yml"
        $syncCount++
    }
    if (-not $DryRun) {
        if ($wfDrift) {
            $wfDir = Join-Path $proj.Path ".github\workflows"
            New-Item -ItemType Directory -Path $wfDir -Force | Out-Null
            Copy-Item $wfSrc $wfDst -Force
        }

        $agentsDst = Join-Path $proj.Path "AGENTS.md"
        if ((-not $DryRun) -and (Test-Path $agentsDst)) {
            $sha256 = (Get-FileHash $agentsDst -Algorithm SHA256).Hash.ToLower()
            $ruleCount = (Select-String -LiteralPath $agentsDst -Pattern '^- \*\*rule_').Count
            $manifestObj = @{
                syncedAt     = (Get-Date).ToUniversalTime().ToString("o")
                ruleCount    = $ruleCount
                agentsSha256 = $sha256
                generator    = "sync-rules.ps1"
            }
            $kuroDir = Join-Path $proj.Path ".kuro"
            New-Item -ItemType Directory -Path $kuroDir -Force | Out-Null
            # "\n" final obligatoire : sans lui, end-of-file-fixer casse Pre-commit
            # a chaque synchro dans tous les repos.
            [System.IO.File]::WriteAllText(
                (Join-Path $kuroDir "rules-manifest.json"),
                (($manifestObj | ConvertTo-Json) + "`n"),
                (New-Object System.Text.UTF8Encoding($false))
            )
            $projSynced += ".kuro/rules-manifest.json"
        }
    }

    if ($projSynced.Count -gt 0) {
        if ($DryRun) {
            Write-KuroLog "  DRIFT -> $($proj.Name) [$ownership] ($($projSynced -join ', '))" -Color Yellow
        } else {
            Write-KuroLog "  SYNCED -> $($proj.Name) [$ownership] ($($projSynced -join ', '))" -Color Green
        }
        $logEntries += "- $($proj.Name) [$ownership] : $($projSynced -join ', ')"
    }
}

# 3. UPDATE LOG
if (-not $DryRun -and $logEntries.Count -gt 0) {
    $logFile = Join-Path $RULES_DIR "SYNC_LOG.md"
    $logHeader = "## $timestamp`n"
    $logBody = ($logEntries -join "`n") + "`n`n"
    if (Test-Path $logFile) {
        $existing = Get-Content $logFile -Raw
        $newContent = "# Sync Log`n`n" + $logHeader + $logBody + ($existing -replace "^# Sync Log\s*\n*", "")
    } else { $newContent = "# Sync Log`n`n" + $logHeader + $logBody }
    [System.IO.File]::WriteAllText($logFile, $newContent, [System.Text.Encoding]::UTF8)
}

if ($DryRun) {
    # CI-verifiable : exit 1 si drift, 0 si propre (B2).
    if ($syncCount -gt 0) {
        Write-KuroLog "DryRun: DRIFT detecte ($syncCount fichier(s), $($logEntries.Count) projet(s)). Relancer sans -DryRun." -Color Red
        exit 1
    }
    Write-KuroLog "DryRun: propre, aucun drift." -Color Green
    exit 0
}

Write-KuroLog "Done. Total syncs: $syncCount" -Color Cyan
