# AGENTS.md -- Kuro Rules Redirector
# DO NOT EDIT THIS FILE DIRECTLY. Master rules are in: ~/Documents/kuro-rules/rules/

You MUST read the rules relevant to your current task. Read R1 first.
To read a rule, use your 'view_file' tool on the corresponding file in the master folder.

## Rule Index
- **rule_01_foundation**: RULE 1: Read Rules First â€” MANDATORY
- **rule_02_mom_test**: RULE 2: Mom Test Gate - Full Detail
- **rule_03_progress_and_time**: RULE 3.5: AI Time Estimation - Full Detail
- **rule_04_36_42_43_47_50_51_52**: SESSION & TRACEABILITY RULES - Full Detail
- **rule_05_06_18_19_38_58_59**: CODE QUALITY RULES - Full Detail
- **rule_07_08_09_10_11_12_13_15_16_17**: PLANNING, ROADMAP & CORE BEHAVIOUR RULES - Full Detail
- **rule_14_validation_and_failure**: RULE 14.5: 5-Risk Failure Mode Table - Full Detail
- **rule_20_21_22_23_24_25_26_27_29_31_32_33_34_35_37_40**: LINEAR, TEAM & PROJECT MANAGEMENT RULES - Full Detail
- **rule_28_linear_review**: RULE 28: Linear Automation and DevOps Review - Full Detail
- **rule_30_branching**: RULE 30: Branch Naming Convention
- **rule_39_41_44_45_54_55_60_61_62_63_74_76**: SECURITY, ENCODING & POLICY RULES - Full Detail
- **rule_46_48_49**: RULE 46: Web/GUI Debugging Protocol (Web-Debug-7)
- **rule_56_57**: RULE 56: v0.dev Landing Page Workflow
- **rule_64_mom_deep**: RULE 64: Negative Mom Test - Deep Verification Protocol
- **rule_65_66_67_68_70_71_72**: BEHAVIOUR, CODE DESIGN & UI RULES - Full Detail
- **rule_75_desk_research**: RULE 75: Deep Desk Research - Full Detail
- **rule_77_79**: RULE 77: L2 Auto-Distribution Pipeline
- **rule_80_epingle**: RULE 80: Epingle Projets Auto-Update - Full Detail
- **rule_81_research**: RULE 81: Scientific Research Protocol - Full Detail
- **rule_82_deep_session**: RULE 82: Deep Session Summary — Full Detail
- **rule_83_discord_summary**: RULE 83: Investor-Ready Discord Summary
- **rule_84_validation_automation**: RULE 84: Validation Pipeline Automation
- **rule_85_portfolio_completeness**: RULE 85: Portfolio Completeness Verification â€” MANDATORY
- **rule_86_kuro_guardian**: RULE 86: Kuro Protocol â€” Project Surveillance & Memory
- **rule_87_ownership_intelligence**: RULE 87: Deep Intelligence & Ownership Verification â€” MANDATORY
- **rule_88_integrity_recovery**: RULE 88: File Integrity & Recovery â€” MANDATORY
- **rule_89_lessons_learned**: RULE 89: Lessons Learned - Rule Creation from Problems Solved
- **rule_91_hardened_versioning**: RULE 91: Hardened Versioning Integrity
- **rule_93_cross_platform**: RULE 93: Cross-Platform Reliability (Windows/Linux)
